### ISSUE TITLE
Implement a single resources page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#103]
## Context
We return the JSON in a GET request to a /resources/{resource_id}, but we should turn this into HTML. :) 

## Acceptance criteria
[ ] Turn JSON into HTML
[ ] Add an "edit" button that only the user who created the resource should see (we can add the functionality later)

**Comment by sebbel** [comment]
@lpatmo can we refine this issue a little bit? 
1. Do we have mockups, 
2. Do we need mockups? 
3. How would this work locally vs live?

**Comment by lpatmo** [comment]
Great questions!

This is the JSON object returned on the page currently: 

```
{
  "guid": "768fc52a-8381-11ea-8994-0242ac120007",
  "author": "James Jones",
  "title": "Here garden school full.",
  "description": "Story indeed ten you west in. North staff rock democratic add nation.\nBetter seem law lawyer anyone professor. More minute well address. Doctor tell environment red week traditional.",
  "url": "https://www.jones.com/explore/explore/app/login/",
  "referring_url": "http://www.gibson.biz/register/",
  "other_referring_source": "https://weiss-adkins.com/",
  "user": {
    "id": 161,
    "username": "olsonemily",
    "first_name": "",
    "last_name": "",
    "is_superuser": false
  },
  "date_published": "2020-04-20T20:37:45.139272-07:00",
  "created": "2020-04-20T20:37:45.139518-07:00",
  "modified": "2020-04-20T20:37:45.139298-07:00",
  "media_type": "Game",
  "paid": true,
  "tags": [
    {
      "guid": "76878a54-8381-11ea-8994-0242ac120007",
      "slug": "place",
      "name": "place"
    },
    {
      "guid": "768ce076-8381-11ea-8994-0242ac120007",
      "slug": "fill",
      "name": "fill"
    }
  ]
}
```

This is a mockup: 

![image](https://user-images.githubusercontent.com/4512699/80304612-ff23ad00-876b-11ea-9b51-8ddc726bb24f.png)

Can you clarify what you mean by the third question?

**Comment by tgrrr** [comment]
Watch out for dangerously injected html

**Comment by bengineerdavis** [comment]
I'll try my hand at this issue. How do I point my draft PR to this?
