### ISSUE TITLE
Implement pagination on the /resources page

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#104]
## Context
At the moment, we're returning all resources on the /resources page. 

When we make a GET request to /resources, the response looks something like:

```
{
    "count": 46,
    "next": "http://localhost:8000/api/v1/resources/?page=2",
    "previous": null,
    "results": [
        {
            "guid": "4e85dbb6-d519-11ea-a622-0242ac130002",
            "author": "",
            "title": "asldfkjadsf",
            "description": "",
```

## Acceptance criteria
[ ] Implement pagination -- the user should be able to click on "next" or "previous" to go to the next or previous pages.

**Comment by pdotsani** [comment]
Waiting on https://github.com/codebuddies/frontend/pull/147 to merge.
