### ISSUE TITLE
[TBD] Add documentation around Github actions

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#110]
## Context
As a contributor, we'd like to know how Github actions work, and what it means for our code. Having some kind of documentation around how this gets triggered and what it does for the codebase would be useful.

## Acceptance criteria
[ ] TBD

**Comment by sebbel** [comment]
I think a paragraph about what GitHub Action is and the benefits / implications for this project along with some links would be sufficient. 
----
We use GitHub actions in the context of this project to run `lint` and `tests` on the changed codebase when a PR is filed. These tools help spot errors in style and logic and reduce the time for reviews. They run automatically and provide insight through checks which are displayed below the PR in question. 
You can read more about them here. https://help.github.com/en/actions
