### ISSUE TITLE
[User Story] CBV3 homepage user story

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#117]
## Context
This purpose of this ticket is to discuss the user story for the V3 home page. 

@adachiu had started working on a WIP which focuses on hangouts and CB Connect:
![image](https://user-images.githubusercontent.com/4512699/87238669-7f949a00-c3ba-11ea-8b83-a5241d2f0189.png)

Our current homepage at https://cbv3.netlify.app: 
![image](https://user-images.githubusercontent.com/4512699/87238690-a9e65780-c3ba-11ea-8ff2-a6f6d44669e1.png)

## Acceptance criteria
When a user lands on codebuddies.org, they'll be informed about:
[ ] Hangouts - a way to meet to pair program or mob program
[ ] CB Connect - a way to fill out a form anonymously and get pointed to another member who might be able to help them
[ ] Resources - a way to search for resources of different levels
[ ] Projects - a way to search for and join open source projects, and meet in hangouts about them
[ ] A way to sign up
[ ] Mention of Slack community (? - currently where most of the community is at)
[ ] Mention of forums.codebuddies.org (? - something we want to emphasize more, since it has archival power)

Note: on our roadmap doc at https://docs.google.com/document/d/1YuVO-v0n73ogoFIwpwJgI1Bkso8sP2mg5zqbX9FB3lU/edit# we also mention `groups` and `learning maps`, but I think they can be prioritized for post-beta.

Note: Feel free to comment if you disagree with the acceptance criteria above, or would like to adjust

**Comment by lpatmo** [comment]
@adachiu When you get a chance, do you mind sharing the SVGs for those images on the home page? I think I'm close to finding time/new contributors to work on a revamped home page. :) Thanks!

**Comment by adachiu** [comment]
SVG files

[svg-hangout-illustrations.zip](https://github.com/codebuddies/frontend/files/5015708/svg-hangout-illustrations.zip)
