### ISSUE TITLE
[Firefox] Potential security issue - `npm run start` bug

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#121]
![image](https://user-images.githubusercontent.com/4512699/88467653-1d459a00-ce8e-11ea-8cbb-0ce057e69ba7.png)

@bengineerdavis was getting this error upon `npm run start`.

**Comment by lpatmo** [comment]
Looks like Ben had an extra security setting which was causing this error in Firefox, so it worked in Chrome! Thanks @watchtheblur for helping us solve :)

**Comment by bengineerdavis** [comment]
@lpatmo I don't remember if we resolved this. Do you all still need me to look into it?

**Comment by lpatmo** [comment]
@bengineerdavis IIRC you asked me to keep it open, but we discovered that you had an extension on Firefox which caused so the issue, so when you created a new browser profile it worked. :) I can close!

**Comment by bengineerdavis** [comment]
Yes that would be great! Let me know what I can reproduce on my end.
