### ISSUE TITLE
[CSS] Fix text overflow problem

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#122]
![image](https://user-images.githubusercontent.com/4512699/88468163-5ed94380-ce94-11ea-9936-b892dd2c8904.png)

h2. Acceptance Criteria
[ ] Fix overflow problem in titles

h2. Ticket Size
1 (small)

**Comment by bkbuilt** [comment]
Will be fixed in new branch.. resolved with "height: '100%'"

**Comment by bkbuilt** [comment]
<img width="1320" alt="Screen Shot 2020-08-02 at 4 24 12 PM" src="https://user-images.githubusercontent.com/50244206/89131677-a5eeb680-d4dc-11ea-953a-35722b09d2e3.png">
