### ISSUE TITLE
[Documentation] Add instructions to contributing.md re: workflow in a forked repo

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#135]
## Context
Pairing with @watchtheblur, I realized that contributors might easily get confused about how to create a PR from a forked repo.

## Acceptance criteria
[ ] Create a checklist for what to do after forking a repo and add it to cocntributing.md

Contents:

1. git pull upstream main
2. git push origin main
3. git checkout -b ISSUE-X-BRANCH // creates a new branch
4. git checkout ISSUE-X-BRANCH // check out the branch if you are not already in it
5. git rebase main // rebase the contents of main into your branch
6. git push --force-with-lease

To open up a new PR, go to github.com/codebuddies/frontend and click on "Pull request" -> "New pull request"

**Comment by peoray** [comment]
To be clear does this mean having a contributing Readme file which explains the process of forking and submitting a PR?

**Comment by lpatmo** [comment]
Yep! ... adding it as a section to CONTRIBUTING.md for now, I think.

**Comment by peoray** [comment]
Okay. I'll delete my current project and try documenting the steps to fully have a functional repo and contributing!

**Comment by lpatmo** [comment]
Thank you @peoray! I think the other ticket (https://github.com/codebuddies/frontend/issues/143) is higher priority, but if you're able to document the steps as you're creating that PR, maybe that would be the easiest approach. Let me know if you need any help!

**Comment by wuworkshop** [comment]
@lpatmo Curious, why should a contributor use `git push --force`. Seeing a flag called `--force` makes me question it.

**Comment by lpatmo** [comment]
Good question! It is one of the common gotchas after rebasing in a local
branch, since the terminal confusingly calls for git pull:

This has a great explanation: https://blog.verslu.is/git/git-rebase/

Also:
https://www.reddit.com/r/git/comments/6jzogp/why_am_i_force_pushing_after_a_rebase/

**Comment by wuworkshop** [comment]
I just read up on the `--force` flag  in the Git reference site and it seems like `--force-with-lease` is safer. 
https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-force-with-lease

Those two links of yours had similar comments about `--force-with-lease`.

From the blogpost, there was this comment posted:
>Instead of –force you should use –force-with-lease.
>
>If new commits are added to the remote branch (by another team member), this command would not update the remote branch (and not overwrite any work).

From the Reddit thread:
https://www.reddit.com/r/git/comments/6jzogp/why_am_i_force_pushing_after_a_rebase/djibwkl/
>One additional comment:
>
>When you force push, it's almost always better to use git push `--force-with-lease` (instead of `git push --force` or `git push -f`). This removes some of the risk involved because if you `pull`, `rebase`, and then someone else pushes a new commit, `--force-with-lease` will fail instead of overwriting the new commit. Someone could still have a copy of the old commits of course, and if they're doing work on those, it can be annoying to reconcile everything, but at least you won't accidentally delete someone else's changes!

**Comment by lpatmo** [comment]
👍 Awesome, let's do that! (And I'll try to change my habits to do `git push --force-with-lease`)
