### ISSUE TITLE
Tests for Search

### ISSUE THREAD

**Issue by tgrrr** [codebuddies/frontend#159]
Increase test coverage for the Search component in `src/components/Resources/index.test.js`

Tests for:
- keyDown
- click on the search button
- Tests expected to fail? Eg. what happens for bett, berty, etc
- Test API and network failures

See:
- https://github.com/codebuddies/frontend/pull/134#discussion_r486147479
- https://github.com/codebuddies/frontend/pull/134#discussion_r486147628

**Comment by lpatmo** [comment]
Thanks for filing issues for those TODOs, Phil :)
