### ISSUE TITLE
Set up Landing Page

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#3]
Use Material UI to develop landing page - https://www.notion.so/Designs-c4aafb2fc93240aea1b033110db076cd#7edcae8b13d34f3284e3a8474d283170

## Implementation Notes
It doesn't have to be pixel perfect, use Material UI components that are closest to what's on the design.

**Comment by lpatmo** [comment]
The landing page/home page UI could use some deeper thinking and discussion, but in the meantime, putting up something would be better than the blank page right now, so am keeping this issue open. :)

**Comment by jesperhodge** [comment]
What are your plans on how to do this? Using React for a landing page is not advisable because of SEO and performance and so on. I can recommend Gatsby so then maybe we can also use some of the Material UI components. Probably it should be a separate project I guess?

**Comment by angelocordon** [comment]
Not terribly concerned with SEO yet but I am vetting SSR with NextJS currently. Will also need to vet Now against Netlify (our current host)

**Comment by lpatmo** [comment]
@jesperhodge That makes sense as we scale, thanks for pointing that out! I
think the first thing we need to draft out is what we want in the landing
page in the first place, heh -- and that ties in with design and user
research work that we don't have as much capacity in.

Feel like we all have a vague and possibly different idea of what we're
building without high quality mockups but that's ok, we will figure it out!
