### ISSUE TITLE
Research React WYWSIG editors

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#31]
We'll need a WYSIWYG editor for users who want to take learning notes about a resource.

https://draftjs.org looks pretty popular. Are there others that we should explore?

**Comment by cptcrunchy** [comment]
I've looked into some OSS WYSIWYGs in the past. I'll take this one please and see what I can find

**Comment by lpatmo** [comment]
Thanks @cptcrunchy! Let me know if you have questions!

**Comment by jtanadi** [comment]
I recently stumbled on [quill](https://quilljs.com/), so adding that to the mix. There's a React component available [here](https://github.com/zenoamaro/react-quill).

**Comment by lpatmo** [comment]
Thanks @jtanadi! (Sorry I totally missed your comment from March)
