### ISSUE TITLE
Extract data from meta tags after users shares a URL to submit as a resource

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#35]
When I paste a resource URL to the /resources submission page, I want the resulting behavior to be similar to what I see if I share a link on Slack or Facebook:

- image (if it exists) gets pre-filled
- the title gets pre-filled
- the description gets pre-filled
- the user can fill out an additional review about what they thought of the resource, and give it a star rating

Steps:
- create a `ResourceSubmit` component
- Find a JS library that helps extract the meta tags

This issue may have to be built on top of #17, or set up separately to focus on the meta tag extraction

**Comment by peoray** [comment]
This sounds interesting. Might want to have a go at it if no one is indicating interest

**Comment by lpatmo** [comment]
Thanks @peoray! As a first step, maybe you could research JS libraries that help extract data from meta tags :)

**Comment by chris48s** [comment]
This library is a good base for implementing this feature: https://github.com/jacktuck/unfurl

**Comment by peoray** [comment]
Thanks @chris48s , I'll take a look

**Comment by peoray** [comment]
@lpatmo I looked at the package Chris linked above, seems good enough. What do you think?

**Comment by lpatmo** [comment]
Looks good! Looks like you can install it with `npm install unfurl.js`. Can you create a branch for this work?

**Comment by peoray** [comment]
Sure, will do. Although, I;ll be needing plenty of assistace. Still not familiar wth the new React APIs and Material UI :)
