### ISSUE TITLE
Hook up search on the front-end with the Django API search

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#4]
See for design reference: https://www.notion.so/Designs-c4aafb2fc93240aea1b033110db076cd#5542b30340554ad984630892464d0139

and issue #3 for implementation notes.

**Comment by lpatmo** [comment]
There are some updated designs here: https://github.com/codebuddies/v3/issues/2

**Comment by lpatmo** [comment]
We have a search component on http://localhost:3000/resources, but it should ideally make a POST request to the search endpoint on DRF whenever a user enters a key.

**Comment by lpatmo** [comment]
Update: the search endpoint now exists! We can make a POST request to `/api/v1/resources/?search=Elm`, for example :)

**Comment by lpatmo** [comment]
h2. Acceptance Criteria
[ ] User is able to type a search term and click submit
[ ] Upon submit, search results are returned, and the keyword the user searched for appears on the screen
[ ] If there are no results, `"keyword" has 0 results` appears on the screen.

h2. Helpful notes
An example search API endpoint: '/api/v1/resources/?search=Elm'

**Comment by BethanyG** [comment]
We currently only have a [**very** basic](https://www.django-rest-framework.org/api-guide/filtering/#searchfilter) search filter enabled in DRF.

**Current search fields are:**  'guid', 'media_type', 'title', & 'description'.  

`author`, `user`, `tags`,  `url` (main & referring), `date_published`,  `date_created`, `date_modified`, and `paid` **are not searched**.

**Comment by lpatmo** [comment]
Branch checked in here: `issue-4-search`

Some remaining todos:
- material UI for the search elements
- integration test

**Comment by lpatmo** [comment]
Update: the PR at https://github.com/codebuddies/frontend/pull/134 by @watchtheblur is pretty close to being merged 🎉

**Comment by lpatmo** [comment]
This is done! https://github.com/codebuddies/frontend/pull/162
