### ISSUE TITLE
[React] Create the skeleton for a Discussion component

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#45]
We don't need any functionality for now, but would be nice to have the skeleton for a `Discussion` component set up: 

![image](https://user-images.githubusercontent.com/4512699/67838042-aec5de00-faad-11e9-956f-d27df33be221.png)

Specs:
- Input box with checkboxes offering three options (hangout proposal, question, pinned message) below
- Each message above should allow for threaded replies (think: the UI on Slack)
- Future work: emoji support
- Future work: ability to sort by `questions`, `pinned messages`, and `hangout proposals`

**Comment by nik72619c** [comment]
I'd like to work on this one

**Comment by wuworkshop** [comment]
@nik72619c All yours. 👍

**Comment by lpatmo** [comment]
Closing this issue in favor of https://github.com/codebuddies/frontend/issues/96, since the design has changed.
