### ISSUE TITLE
Create user stories to propose project features and functionalities aligned to the user's needs and their goals

### ISSUE THREAD

**Issue by claucvk** [codebuddies/frontend#52]
User stories are often expressed in a simple sentence, structured as follows:

“As a [person in a particular role], I want to [perfom an action or find something out], so that [I can achieve my goal of].”

Steps:

1) Identify the different users and their corresponding characteristics. Ex: role in the platform, tasks to perform, age, coding experiencing... Gather any information that could be helpful to describe the user. This could be a separate ticket to developing a persona.

2) For each group of users create the user stories following the example above. Specifying the user, the action to perform, the goal achieved, and the page or section where the story occurs.

3) Each of these user stories could lead to some case scenarios or sub-stories with more details. This could be a different ticket or issue.
 
The arrangement of the information could be as follow:
page > user type > user story > scenarios

Some useful links: 
https://www.smashingmagazine.com/2018/02/comprehensive-guide-user-experience-design/

https://www.mountaingoatsoftware.com/agile/user-stories

https://www.atlassian.com/agile/project-management/user-stories

**Comment by lpatmo** [comment]
Thank you for writing this up, @claucvk! :)

**Comment by lpatmo** [comment]
I wrote up a quick draft doc of user personas: https://docs.google.com/document/d/1gA25rlMv91sIEufohZKewHVegHPecSArb35K6NIJcPA/edit

![image](https://user-images.githubusercontent.com/4512699/73604609-57218d80-4548-11ea-907a-91f56bfe99bf.png)
