### ISSUE TITLE
Remove timestamps from /resources page

### ISSUE THREAD

**Issue by bkbuilt** [codebuddies/frontend#54]
For resources page, styling is messed up in Firefox (such as timestamps). However, it displays properly in Chrome.

**Comment by peoray** [comment]
@bkbuilt I can't reproduce this issue. Can you send a screenshot of your browser?

**Comment by bkbuilt** [comment]
<img width="1680" alt="Screen Shot 2020-02-21 at 11 34 19 AM" src="https://user-images.githubusercontent.com/50244206/75052895-5bcdc780-549e-11ea-9e2f-28d22c5a0a52.png">

**Comment by lpatmo** [comment]
@adachiu also proposed removing timestamps entirely from the /resources page in https://www.figma.com/file/wXMeX9xgYTcVKNJ1XT9ZQ5/cbv3poc?node-id=0%3A1. 

I'm going to update the title of this issue to be about removing the timestamps.
