### ISSUE TITLE
Refactor styles to be consistent

### ISSUE THREAD

**Issue by jesperhodge** [codebuddies/frontend#73]
Since this project is intended to use Material ui with styled components, let’s also replace the css files with styled components.

**Comment by jesperhodge** [comment]
I’ll do this if it’s approved for doing

**Comment by lpatmo** [comment]
Question on global styles: do you think we may need some for things like 

```
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
    "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

code {
  font-family: source-code-pro, Menlo, Monaco, Consolas, "Courier New",
    monospace;
}
``` and 
```
a:link {
  color: #00008b;
  text-decoration: none;
}

a:visited {
  color: #6807f9;
}
```
?

Or is the idea that these styles get scoped to one parent/wrapper component (App)?

**Comment by jesperhodge** [comment]
Well I think it does make sense to keep some global styles, but I would scope things to respective components / Material UI elements wherever possible, and also scope some things to `App`. The nice thing is that you can still add things like `a:link { }` inside the styled component for App then, normal nesting works perfectly fine with styled components, and you can also override it wherever you need based on your JavaScript and have a `ThemeProvider` that holds variables for all your stuff, so you switch things out in one central location where needed. ( Though I think the Material UI theme provider might be sufficient for us for now.)

**Comment by jesperhodge** [comment]
One of the benefits is that in that case, we can for example scope `a:link` to `App` - then instead of having a hardcoded color we set different color variables (like `codebuddies-green`, `codebuddies-red`) and we can just do stuff like `a:link { color: ${ codebuddies-red }; ` and that can even be changed dynamically in javascript (for example you click a button and cause your styles to change even.) It is a huge advantage.

**Comment by lpatmo** [comment]
Cool, thanks for clarifying! Feel free to go ahead :)

**Comment by jesperhodge** [comment]
I opened this issue based on what I saw in the code (e.g. `App.css`) and my (mistaken...) memory that Material uses styled components. Anyway, I checked how Material UI works together with Styled Components.

I realized that Material UI uses their own styling solution that is very similar to Styled Components, and the nice thing is that they expose it for us to use and have a nice documentation. I would actually like to try this on top of the Material UI components we want to use anyway, as it will work nicely together and seems pretty good. https://material-ui.com/styles/basics/ --- it is not much different than styled components anyway.

**Comment by lpatmo** [comment]
Sounds good! I totally misremembered that material UI uses styled
components too, but is actually not exactly styled components but something
very similar.

**Comment by jesperhodge** [comment]
@lpatmo I'm kind of quick to be confused with a new codebase, I somehow misunderstood how the Material UI styles were added in the first place (you are after all using their hooks API), so I made a few silly statements in here, but I'm learning. So I'm still going to work on the `App.css` file to make stuff consistent with this, I think the Pull Request will explain and make more sense when I'm ready. Sorry for the confusion!

**Comment by angelocordon** [comment]
I was looking over the styles API from Material the other day and I don't particularly love it... I thought we had StyledComponents initially, but maybe that was not implemented. @jesperhodge, I'd like to look into a way where we can implement global styles and pass that down to Material. Alternatively, if it's better to just have StyledComponents in the first place, that would be grand. 

Would you be interested in looking into that?

**Comment by sebbel** [comment]
Just to revive this. I have had some great success with `theme-ui` on a few toy projects. maybe we could try that out if its compatible with material?
