### ISSUE TITLE
[Discussion] Signup magic links

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#77]
**Is your feature request related to a problem? Please describe.**

Magic links where user would input their email and get a link to signup

Let's discuss advantages/disadvantages, including:
- Can signup magic links exist alongside a normal username/password flow?
- Can they exist alongside GitHub auth?
- What would the implementation look like?

**Comment by angelocordon** [comment]
@lpatmo - let's move this discussion to the backend repo - I think most implementation would be handled by the API for this. Additionally, can we opt out of social auths for now until a stable release comes out?

**Comment by lpatmo** [comment]
> Additionally, can we opt out of social auths for now until a stable release comes out?

Yep!

Yeah, makes sense to have the implementation discussion be for `backend`. Btw also don't think we need to pursue it right now (in terms of priority issues), unless someone has an interest.

**Comment by angelocordon** [comment]
Moving to https://github.com/codebuddies/backend/issues/101
