### ISSUE TITLE
Add missing PropTypes for components

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#82]
## Context
Currently, we have two files where we are missing prop types (Resources/ResourceCard.js and Resources/ResourcePage.js). These can be found by running `npm run lint` and it should show what is currently missing. At the time of this writing, the missing prop types are:

```bash
/react-concept/src/components/Resources/ResourceCard.js
  47:32  warning  'id' is missing in props validation           react/prop-types
  47:36  warning  'title' is missing in props validation        react/prop-types
  47:43  warning  'created' is missing in props validation      react/prop-types
  47:52  warning  'description' is missing in props validation  react/prop-types
  47:65  warning  'url' is missing in props validation          react/prop-types

/react-concept/src/components/Resources/ResourcePage.js
   8:25  warning  'matchProps' is missing in props validation                  react/prop-types
  13:60  warning  'matchProps.match' is missing in props validation            react/prop-types
  13:66  warning  'matchProps.match.params' is missing in props validation     react/prop-types
  13:73  warning  'matchProps.match.params.id' is missing in props validation  react/prop-types
  23:18  warning  'matchProps.match' is missing in props validation            react/prop-types
  23:24  warning  'matchProps.match.params' is missing in props validation     react/prop-types
  23:31  warning  'matchProps.match.params.id' is missing in props validation  react/prop-types
```

## Implementation
1. Run `npm run lint` and find out which components have missing prop types
1. Address missing prop types
1. Change the rules in the eslintrc file so that missing prop types return an error instead of a warning

## Acceptance criteria
- [x] No more missing prop types
- [x] ESLint rule is updated and is working correctly

**Comment by peoray** [comment]
@angelocordon will the `id` be a string or a number. Currently setting it as a string

**Comment by angelocordon** [comment]
`id`s will be numbers coming from the backend in this case
