### ISSUE TITLE
Set up CI pipeline 

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#83]
## Context
Set up a CI pipeline that runs Jest and ESLint on Pull Requests to master.

## Acceptance criteria
- [x] Github Actions should be running on pull requests to master to verify that tests pass along with ESLint.

**Comment by angelocordon** [comment]
Looks like their open source platform might be migrating to their .com site? https://devops.stackexchange.com/questions/1201/whats-the-difference-between-travis-ci-org-and-travis-ci-com/4305

Unsure if it's worth going ahead and signing up for their Open Source Tier in their .com site or keep using their .org platform

**Comment by angelocordon** [comment]
@sebbel let me know if you make some headway with Github Actions and we can update this issue to reflect that.

**Comment by tgrrr** [comment]
Ive had a better experience with CircleCI

**Comment by lpatmo** [comment]
@tgrrr Curious if you could expound on some of the benefits you've had working with CircleCI vs TravisCI. Thanks!

**Comment by tgrrr** [comment]
Hi Linda,

I've just found the cli, the website's UI, and integrations simpler.

It also seems to be the industry standard down here.

[Here's a fairly good comparison[(
https://hackernoon.com/continuous-integration-circleci-vs-travis-ci-vs-jenkins-41a1c2bd95f5
)

Cheers

**Comment by sebbel** [comment]
@tgrrr thanks for chiming in. We were looking to use github actions, because then we'd have code and lints/tests on github. Do you have thoughts on that?
Else, I'd +1 on circleci, I was faster to get up to speed with it.

**Comment by angelocordon** [comment]
I'm open to any so long that something is running our tests! :) 

We've used Travis before for our past CB projects and had a pretty easy setup. I've used CircleCI for past professional work, but I'm not sure what their open-source plan is in comparison to Travis (and GitHub actions).

**Comment by lpatmo** [comment]
Ahh, I didn't even realize that Github Actions is a new thing that is competing directly with services like CircleCI or TravisCI. Whoops.

I'm still uncertain whether it would be better to run tests on Github Actions or during the Netlify build. Anyone have experience with this? 

https://community.netlify.com/t/guide-for-deploy-using-github-actions/2981
https://community.netlify.com/t/common-issue-testing-your-netlify-builds/1456

**Comment by tgrrr** [comment]
IMHO, we should use CI similar to git flow.

Ie. We can automatically run tests by merging a PR into a dev branch which
should run tests/lint/etc with some kind of CI (CircleCI/TravisCI/Github
actions/gitlab CI).

After tests have passed, it should then trigger a Netlify staging site.
Seriously, it generates a custom staging site for every git push. [Details
here](https://www.netlify.com/products/build/)

Then after we have a `FE release` that syncs with the `Django BE's API`, we
can merge the dev branch into master, which triggers the Netlify production
build.

Tada.

**Comment by angelocordon** [comment]
Yup, I believe that's the idea.

**Comment by billglover** [comment]
It would be very useful if we could spit out a Docker image containing the latest front end. Would love to include this as part of the local back end set up for the following reasons:

- Backend contributors can see latest front end without installing or understanding build process
- Contributors can have a fully functioning version of CB on my laptop and work offline

Ideally this should be spat out the end of the build process and tagged with the version that has been released to live. The container image should be stored in the CodeBuddies Docker Hub organisation.

**Comment by billglover** [comment]
**Note:** codebuddies/backend is using GitHub actions for running tests and builds on PRs
