### ISSUE TITLE
Set up Jest with Babel, and React Testing Library

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#85]
## Context
We're not able to use ES6 imports with Jest. We need to configure Jest to be used with Babel.
Configure the project to use React Testing Library with Jest.

## Acceptance criteria
- [x] Be able to use ES6 imports in test suites
- [x] Have tests with Jest + React Testing Library for AuthForm components.

**Comment by tgrrr** [comment]
There's a separate thread about writing tests with Cypress, btw. Including
Jest syntax in Cypress.

**Comment by angelocordon** [comment]
Hmm, which thread is that? Is that an active issue somewhere?
