### ISSUE TITLE
Add Form Validations to AuthForms

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#93]
Auth Forms should validate required fields and types based on what the API expects to have.

**Comment by lpatmo** [comment]
Cross-posting a comment I made in #55 re: validation libraries -- 

I'm thinking we could use react-form-hooks, based on this article:
https://blog.logrocket.com/react-hook-form-vs-formik-a-technical-and-performance-comparison/

A relevant thread: mui-org/material-ui#18269

Was curious if anyone else had recommendations for validation with Material-UI too! I asked this on Slack in the #reactjs channel, and got `Formik`.

**Comment by peoray** [comment]
I'm familiar with Formik and Yup. Which one should I go on with. React hooks form looks promising also.

**Comment by angelocordon** [comment]
Based on that blog post from @lpatmo, I'm inclined to lean in on React Hook Form. I haven't played around with it yet, but might be worth experimenting with it @peoray 👍
