### ISSUE TITLE
Add monitoring tool for frontend bugs

### ISSUE THREAD

**Issue by angelocordon** [codebuddies/frontend#94]
Look into setting up Sentry or Bugsnag (check to see if they have open-source plans first)

**Comment by wuworkshop** [comment]
Bugsnag has an open-source plan. Apply here: https://www.bugsnag.com/open-source

Sentry's code is open-source: https://sentry.io/_/open-source/

**Comment by sebbel** [comment]
I'd advocate for Sentry. Can you @lpatmo create a codebuddies account and we'll just go from there?

**Comment by lpatmo** [comment]
Thanks all, will apply at https://sentry.io/for/open-source/!
