### ISSUE TITLE
Hangout user flow

### ISSUE THREAD

**Issue by lpatmo** [codebuddies/frontend#97]
Logging notes here.

**Comment by lpatmo** [comment]
Logging a discussion thread @sunu and @BethanyG and I just had on Slack re: terminology around how to describe the different sorts of hangouts:

`meet` -> schedule a meeting to do anything really (probably study group), either private or public
`pair` -> 1:1 usually, but you can optionally make it open to observers
`hack` -> work on open source project together (?)
`demo` -> show off your projects! show & tell! 

(On CBV2, the current codebuddies.org site, the types were `teaching`, `silent`, and `collaborative`. We're tentatively updating this to be `meet`, `pair`, `hack`, and `demo`)

**Comment by lpatmo** [comment]
On our [figma](https://www.figma.com/file/wXMeX9xgYTcVKNJ1XT9ZQ5/cbv3poc?node-id=0%3A1), I also documented the different types of situations a user might find themselves starting or stating their interest in a hangout.

**Comment by lpatmo** [comment]
Some really nice icons we can use to reflect public vs. private, silent vs. non-silent etc. hangouts: https://thenounproject.com/ (h/t @BethanyG and @wuworkshop)

**Comment by angelocordon** [comment]
If we're going to use icons, I'd prefer we use an icon set to enforce consistency (both visually and code). 

https://ionicons.com/
https://feathericons.com/
https://fontawesome.com/

**Comment by lpatmo** [comment]
Copying/pasting from Slack discussion threads:

linda (she/her):spiral_calendar_pad:  3 days ago
:star2: Part of a successful pairing session is establishing guidelines for how to pair program, including the idea of establishing a goal and checking in during the middle/end about whether that goal was met. We should relay this info. to people who sign up to pair.
:+1::skin-tone-3:
4

bethanyg  2 days ago
We'll need some rules scoped for matching - what will be the criteria?  What happens if a pairing isn't successful?  How does information get shared?  We also (on the backend) need to know what will and will not be tracked in a user's profile - and what fields will be used for matching.  Also what the endpoint will look like.


linda (she/her):spiral_calendar_pad:  2 days ago
Yep, good questions! I think we’ll want to dive into that as soon as we’re decided on the new direction. One feature I think is important to include in the beginning, for example, is the idea of being able to flag another user/block someone from being matched with the user.

bethanyg  2 days ago
Definitely.  I think leveling is a big deal as well.  Beginner doesn't always mean the same thing to everyone.
:heavy_plus_sign:
2


bengineerdavis:spiral_calendar_pad:  1 hour ago
I like this, a few things that come to mind: (apologies in advance if theses idea area already being considered)
A pairing request that could be asynchronous--I could define a 'legal' request for a pairing session without having another partner--because it's likely I won't have one when I want one at the instant, and could then link to it in a chat or forum for codebuddies, but before it become an official hangout. Conversely, people can do searches on open pairing requests. Also, that people could request people join a pairing session or define the session itself.
what should be the minimum requirements to submit a pairing request?


linda (she/her):spiral_calendar_pad:  3 days ago
:star2: :thread: Product direction proposal: finish up resource search / resource page / resource POST; then move onto “find a pair programming partner” direction and start by redesigning the home page to emphasize the pairing element.
Resources, projects, etc. will be secondary-emphasized features on the home page. (edited) 
:+1::skin-tone-3:
4


bethanyg  2 days ago
What are the implications here for the backend/API work?  We don't have an endpoint for paring, nor any models.  We also don't have any user table changes scoped for pairing.  In fact, pairing and "codebuddies connect" were not on our MVP or v1 release plan.  Are we shifting to that?

bethanyg  2 days ago
Does this mean that the Hangouts work is being shelved?

linda (she/her):spiral_calendar_pad:  2 days ago
The proposal is that the focus will be on Hangouts — but from a pairing perspective, and not from a “we expect you to be a meetup organizer” perspective. We still need to figure out the exact UI flow re: what it means to schedule a pairing session, but I think once everyone is aligned on the designs we can create tickets for what endpoints we need, and what the DB schema should look like.

bethanyg  2 days ago
Well, there is substantial work there, so I think it's more than filing a few issues.  Is this endpoint going to be called "pairing" or "hangouts"?  Will being paired be a separate action from scheduling Hangouts?  Will there no longer be any sort of hangout that isn't a pairing session?  What if the match doesn't work?  Are hangouts going to be linked to users, or are they their own entities (read:  their own table in the DB).

bethanyg  2 days ago
So - having a hangout that is discussion based is not going to be possible?  These will now only be programming focused?

linda (she/her):spiral_calendar_pad:  2 days ago
Yes — before any of those issues are filed, we should figure out the design flow first, and that involves answering those great questions you raised.
Having a hangout that’s discussion-based will definitely still be possible — it’ll be the default type of hangout. The “pairing” aspect is to ensure that when someone schedules a hangout, at least one other person will be there.

bethanyg  2 days ago
Sounds like a meeting/discussion/session on what things go in a user profile, and what pairing toggles are needed might be in order.

linda (she/her):spiral_calendar_pad:  2 days ago
The problem on codebuddies.org/hangouts right now is that:
1) it feels too much like scheduling a public meetup, and most people won’t do it;
2) when someone schedules a hangout, there is low likelihood that they’ll get any attendance unless they had set up a time with someone in advance
The “setting up a time with someone in advance” is the problem that I hope will be tackled by the “pairing” angle — i.e. you can propose a hangout, then get at least one person who’s interested to agree to that time, then make it a public hangout or private hangout depending on what you two want

bethanyg  2 days ago
Maybe there is an "extended profile" that keeps pairing info for a user, and  an interface that lets them control which fields are used for matching them with others? (edited) 
:thinking_face:
1


bethanyg  2 days ago
Getting someone interested is a little different from "the system will match you"

bethanyg  2 days ago
one might be as simple as having a list of "open to join" hangouts -- although that has failed us in the past.

bethanyg  2 days ago
The other is more complex, and has privacy implications...or could.

linda (she/her):spiral_calendar_pad:  2 days ago
Yeah, I wasn’t really thinking “the system will match you” at all, but more like a public listing of… hangout/pairing proposals

linda (she/her):spiral_calendar_pad:  2 days ago
“Open to join” works as long as it has two people already committed, imo

bethanyg  2 days ago
Could there be a way of counting down/designating the difference?

bethanyg  2 days ago
So - everything is open to join, but if there aren't two willing to meet by x number of hours before the hangout, the initiator is notified that their hangout won't happen?

bethanyg  2 days ago
or maybe not that..but if there are no takers by x number of days out, there is a note sent to the person who proposed that maybe they should try again?

bethanyg  2 days ago
or the list could be sorted so that the ones with less than two people pop to the top?

linda (she/her):spiral_calendar_pad:  2 days ago
Maybe we have two separate lists:
Proposals — e.g. person open to pairing/studying with anyone in the next month on X. Threads will be about figuring out the time that a second person (or group of people) is willing to join.
Live and upcoming sessions — open to everyone hangouts that have been scheduled from the preceding page.
(edited)

bethanyg  2 days ago
That makes sense.  Unfortunately (because, it's me) I have a couple of questions there:
 What if I'm not open to pairing with just anyone, or I am lost as to how to find someone who would be a good fit?
What if the session is closed?  Are we going to have a public/private toggle?
What if a session is open to observation -- but for whatever reason closed or limited in participation? e.g. You are helping me resolve a React issue via pairing, and people can watch..but there are only two - three participating.

linda (she/her):spiral_calendar_pad:  2 days ago
Ohh, was thinking (disclaimer: not sure if anyone else thought about this the same way) is that after the proposal is published, other users can respond if they’re interested, and the OP picks who they want to schedule a pairing session with. And they can get a feel for those other users by looking at their user profiles.
Yes, I think we should have a private/public toggle for hangouts — which will be a new feature. From the developers’ perspective we can still count how many connections CB helped make, but hangouts will not all have to be automatically public.
++. There might be a way to code this in this Zoom API (allow observers only), but I think the easiest way to enable this is to be upfront that X and Y are pairing, and others can join to observe. Maybe open to observation vs. `open to participants` should be optional radio boxes the hangout creator can tick off?
make private
open to observers
open to collaborators
(something like that)

bethanyg  2 days ago
Yeah.  We don't want too many leavers or buttons..but I think we've always had a problem with conveying to people what they can/cannot "do" with a hangout.

bethanyg  2 days ago
The whole "silent" thing...lol

bethanyg  2 days ago
ooh.  "meeting for motivation" maybe?  or "accountability meeting" or "keep me accountable!"
:ohyeah:
2


linda (she/her):spiral_calendar_pad:  2 days ago
It was an idea before its time, but it’s also been the least-used type of hangout scheduled, I noticed. The 24/7 coworking hangout (with optional voice) might be a good replacement for it, given enough traffic.

linda (she/her):spiral_calendar_pad:  2 days ago
I LOVE “keep me accountable”!

linda (she/her):spiral_calendar_pad:  2 days ago
And “meeting for motivation” is great too

linda (she/her):spiral_calendar_pad:  2 days ago
Now… how do we present these ideas to @ada without overwhelming her :sweat_smile:
In all seriousness, I’m thinking we should schedule another design meeting within the next few weeks to go more in depth on all these details, and come up with a final sketch for hangout user flow. I can create a doodle and prepare an agenda doc containing everything we’ve discussed so far when folks are ready.
:+1::skin-tone-5:
1
:heavy_plus_sign:
1


bethanyg  2 days ago
I think that would be good.  Some of this is UX/UI -- and some is "WTF do we put in the DB and WHERE?" .. and I can get a head start on some of it..but also want to make sure that we keep it as flexible as possible.

bethanyg  2 days ago
So..it feels like there are six things:
 Hangouts backend endpoint, DB, API, scheduling/tracking
 User backend extended profile, DB (do we dump this into users??) changes
 Changes to resources backend model and endpoint for beginner friendly
 UX/UI/flow for Hangouts
 UX/UI/flow for discovery (what I am calling it) or home page for hangouts
 Change to frontend resources page for beginner friendly

bethanyg  2 days ago
AAAAAH!
 Ohh, was thinking (disclaimer: not sure if anyone else thought about this the same way) is that after the proposal is published, other users can respond if they’re interested, and the OP picks who they want to schedule a pairing session with. And they can get a feel for those other users by looking at their user profiles.
So hangouts have different states?  A hangout is created first without a date or any attendees attached, then moves to a different status when the attendees go above 1?

bethanyg  2 days ago
And then goes to a third status when a date is assigned?

linda (she/her):spiral_calendar_pad:  2 days ago
Yeah… a good question @j asked on stream yesterday was roughly “how can we be sure that cbv3 is more successful/gets more user engagement than cbv2?” and so part of our theory of change is the new emphasis on pairing partners, but we need to be very considerate about user flow and design before we build it out. Ideally we should be building out the minimum of features :stuck_out_tongue:
^ That list looks good. Part of #6 is a bunch of FE features we still are in the middle of implementing — like search, sprucing up the resource detail page, the “create a resource form” + validation + tests, etc. @Brent, @j, and @bengineerdavis so far have been helping with that.
 So hangouts have different states? A hangout is created first without a date or any attendees attached, then moves to a different status when the attendees go above 1? And then goes to a third status when a date is assigned?
Ohhh yes, exactly!

bethanyg  2 days ago
So that flow really really needs to be thought out carefully.  Also how those different states get filtered/displayed.
:100:
1


linda (she/her):spiral_calendar_pad:  2 days ago
In terms of design process / iteration, I propose using figma + figma comments to iterate on that flow. (You can toggle show/hide comments by clicking on the top left “chat” icon)

FigmaFigma
cbv3poc
Created with Figma (95 kB)
https://www.figma.com/file/wXMeX9xgYTcVKNJ1XT9ZQ5/thumbnail?ver=thumbnails/86c48644-158c-49fa-ac71-a0848ff56a31

bethanyg  2 days ago
for the fronted, that makes sense...but for the backend, we might need something different.

bethanyg  2 days ago
For instance, we'll need at least a "status" field in the model .. but we may also need  "current/future/stale"  fields as well.

bethanyg  2 days ago
and "scheduled" vs "unscheduled"

bethanyg  2 days ago
I'm not on figma.  Is there a CB account?

linda (she/her):spiral_calendar_pad:  2 days ago
It looks like you should have edit accesss… do you see a barrier when you click on that figma link?
image.png 
image.png



bethanyg  2 days ago
Yeah.  I don't have an account.

bethanyg  2 days ago
was that through social auth via github?  Found it. (edited) 
:heavy_check_mark:
1


ada:corgi:  2 days ago
@bethanyg RE: if there are no takers by x number of days out, there is a note sent to the person who proposed that maybe they should try again? — We did talk about an idea of proposing hangouts set with an expiry date/time.
There could be 2 areas to show the CB Connect’s list of hangouts available:
Main CB connect page
list showing usernames of hangout initiators and their proposed date/time and topic tagged (could be filtered for search)
Specific resource or project page
list showing usernames that’s specifically interested in having a hangout about the particular resource or project.
It may promote quicker matches if user can see the list of interested people on the same topic that they are studying/working on. This would be different than the list on the main CB Connect page as there’s less to search and filter through.

RE: what if I’m not open to pairing with just anyone — The list will show the usernames available and you can connect with them on Slack first to see if it’s a good fit. Or, we can also make it a requirement when initiating hangouts, to tag :label: level that they’re looking for “beginner” or “advanced”...and :label: whether or not it will be private/public

ada:corgi:  2 days ago
@bethanyg  @linda (she/her) Would different states for hangout increase the drop off rate of following through? Someone who might initially be interested may lose interest if there’s so many “steps” until a hangout is official?

linda (she/her):spiral_calendar_pad:  2 days ago
@ada You’re right :slightly_smiling_face: What if we kept the path where if someone knows the exact time they want to schedule it (including the option of starting an impromptu one now), they still can? Otherwise, the path is to fill out the “I am looking for ____” path

bethanyg  2 days ago
@ada - apologies.  I should have been clearer on that.  Whether or not is it represented in the UX/UI, we will need to have different states on the backend for hangouts, since we won't be able to create them with every detail in one shot, and we'll want to separate out those that are open for RSVP vs those that are not.
But you have a very good point:  we don't want to set up too many details, too many fields or too many steps in the user flow - because any one of those could cause drop off or loss of activation energy.  But even with two paths, I think we'll need at least two states on the backend (we might need three or more) :
 Something is missing info (like yet to be scheduled or yet to have attendees, or some such)
 Something has a minimum of two committed attendees & a date/time
 Something has been called off or cancelled??
 Something has been re-scheduled or moved??
I'm also thinking of a user scenario where I say, have three things I am looking for:
 I want an accountability buddy for my SQL (cuz I need to practice)
 I am also looking for a coding partner on a project, and
 I want an ongoing study buddy for data science. 
Maybe they're all "I am looking for ___" -- but I'd expect to have an area where I can see them all, and some sort of flow for each as people become interested.  I might want to review who/what/when before I really finalize.....so....dunno what that means.  Maybe an area in my profile where I can see who has said they are interested??  Or is that a page in the UI where I can filter by which hangouts I've made?  Maybe I'm just tired and over-thinking this.  LOL. (edited) 

ada:corgi:  20 hours ago
@linda (she/her) Yes I think that makes sense, having both: 1) setting exact time  2) instant pairing/meeting

ada:corgi:  20 hours ago
@bethanyg In the user scenario where you have 3 things you’re looking for, you can propose 3 separate hangouts and set the time date and wait for people to connect with you. IF in any case you don’t have a timeframe in mind to do those 3 things you’re looking for, then maybe it could be an open-ended hangout you create with no time set. Just wait until someone sees your hangout proposal and connect with you to arrange a future time together. Or you can revise the open-ended hangout proposal at a later date when you know you’re ready to set a time.
And yes I would imagine the profile page would list out your history of hangouts created (Active/Non-active/Archived) which are also tagged.

**Comment by lpatmo** [comment]
Discussion continued here: https://github.com/codebuddies/frontend/discussions/138

**Comment by BethanyG** [comment]
Removing stale, as this discussion is ongoing.
